def _(s:str) -> str: ...

def download(url:str, filename:str, hash:str|None=None) -> None: ...

def unpack(archive:str, destination:str) -> None: ...

def exists(filename:str) -> bool: ...
def remove(filename:str) -> None: ...
def move(old_filename:str, new_filename:str) -> None: ...
def mkdir(dirname:str) -> None: ...
def info(message:str, **kwargs) -> None: ...
def processing(message:str, **kwargs) -> None: ...
def error(message:str, **kwargs) -> None: ...

def run(*args, **kwargs) -> None: ...
